Repository aaaguirrep/offensive-docker, pull requests merged in 2020-09, with the labels that each got.

#3 Added @bo0om fuzz.txt wordlist
  Dockerfile
Labels: enhancement

#4 Update README.md
  README.md
Labels: documentation

#5 Update README.md
  Dockerfile
  README.md
Labels: bug, documentation
